added getting started readme and documentation
david-fisher/320-S21-Track2 pull request #81
Opened 2021-03-17 01:33 UTC by HannanSolo

#52 
#50 

resolved :) 

:1st_place_medal:

2021-03-17 17:52 UTC, jeffreyttran commented on apache_mod_wsgi/README.md
> +Enter these into your terminal in order.
Feel like having a colon instead of a period would make it clearer to indicate what commands should be written down.

2021-03-17 17:52 UTC, gzhihongwei requested changes
If you could fix these small things, it should be good to go.

2021-03-17 17:52 UTC, gzhihongwei commented on apache_mod_wsgi/README.md
> +Now we need to create or apply a SSL cert for the application domain on your shibboleth SP.
Should for "for your Shibboleth SP"

2021-03-17 17:52 UTC, gzhihongwei commented on apache_mod_wsgi/README.md
> +
Can remove this empty line.

2021-03-17 17:52 UTC, gzhihongwei commented on apache_mod_wsgi/README.md
> +Then we need to edit the service provider configuration file(shibboleth2.xml) using
Use backticks for `shibboleth2.xml`.

2021-03-17 17:52 UTC, gzhihongwei commented on apache_mod_wsgi/README.md
> +![](shibboleth_status.png)
No AlT-TeXt???????????????

2021-03-17 17:52 UTC, gzhihongwei commented on apache_mod_wsgi/README.md
> +![](login.png)
No AlT TeXt??????

2021-03-17 17:53 UTC, jeffreyttran commented on apache_mod_wsgi/README.md
> +Enter these into your terminal in order.
Feel like having a colon instead of a period would make it clearer to indicate what commands should be written down.

2021-03-18 01:38 UTC, gzhihongwei commented on apache_mod_wsgi/README.md
> +For a localhost project we are creating a self signed certificate.
Add a comma after "project"

2021-03-18 15:58 UTC, gzhihongwei approved these changes
Looks good to go.

2021-03-18 15:59 UTC, merged